package modelo;
// Generated 08-mar-2015 18:47:49 by Hibernate Tools 3.6.0



/**
 * Consulta generated by hbm2java
 */
public class Consulta  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apellido;

    public Consulta() {
    }

    public Consulta(String nombre, String apellido) {
       this.nombre = nombre;
       this.apellido = apellido;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }




}


